import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#44403c",
        "on-error": "#ffffff",
        "inverse-surface": "#372f2b",
        "on-primary-fixed-variant": "#623f18",
        "outline-variant": "#d4c4b7",
        background: "#fff8f6",
        "on-primary-fixed": "#2c1600",
        surface: "#fff8f6",
        "tertiary-fixed": "#e9e1db",
        "secondary-fixed": "#ffdcc7",
        "inverse-on-surface": "#fdeee8",
        tertiary: "#625d59",
        primary: "#7d562d",
        "inverse-primary": "#f0bd8b",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ccc5c0",
        "primary-container": "#d4a373",
        "on-tertiary-fixed-variant": "#4a4642",
        "on-tertiary": "#ffffff",
        secondary: "#735948",
        "on-secondary-container": "#785d4c",
        "surface-tint": "#7d562d",
        "surface-dim": "#e6d7d2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#50453b",
        outline: "#82756a",
        "primary-fixed-dim": "#f0bd8b",
        "surface-bright": "#fff8f6",
        "on-secondary-fixed": "#2a170a",
        "surface-container-highest": "#eedfda",
        "surface-container": "#faebe6",
        "secondary-container": "#fdd9c3",
        "surface-container-high": "#f4e5e0",
        "secondary-fixed-dim": "#e2c0ab",
        "tertiary-container": "#b2aba6",
        error: "#ba1a1a",
        "surface-variant": "#eedfda",
        "on-secondary-fixed-variant": "#5a4232",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ec",
        "primary-fixed": "#ffdcbd",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1e1b18",
        "on-primary-container": "#5b3912",
        "on-background": "#211a17",
        "on-surface": "#211a17",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      maxWidth: {
        "max-content-width": "72rem",
      },
      spacing: {
        "space-2xs": "0.5rem",
        "space-2xl": "6rem",
        "margin-desktop": "3rem",
        "space-xl": "4rem",
        "max-content-width": "72rem",
        "space-3xl": "9rem",
        "space-sm": "1rem",
        "margin-mobile": "1.25rem",
        "space-3xs": "0.25rem",
        "space-lg": "2.5rem",
        "space-xs": "0.75rem",
        gutter: "1.5rem",
        "space-md": "1.5rem",
      },
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        serif: ["Cormorant Garamond", "serif"],
        display: ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "title-md": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Cormorant Garamond", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "label-subtle": ["Montserrat", "sans-serif"],
        "headline-lg": ["Cormorant Garamond", "serif"],
        "headline-md": ["Cormorant Garamond", "serif"],
        "display-mobile": ["Great Vibes", "cursive"],
        "headline-sm": ["Cormorant Garamond", "serif"],
        script: ["Great Vibes", "cursive"],
        calligraphy: ["Great Vibes", "cursive"],
        brush: ["Alex Brush", "cursive"],
        elegant: ["Cormorant Garamond", "serif"],
        "sans-clean": ["Montserrat", "sans-serif"],
        urdu: ["Noto Nastaliq Urdu", "serif"],
      },
      fontSize: {
        "body-lg": [
          "18px",
          { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "300" },
        ],
        "title-md": [
          "18px",
          { lineHeight: "26px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "20px", letterSpacing: "0.015em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.2em", fontWeight: "600" },
        ],
        "label-subtle": [
          "13px",
          { lineHeight: "18px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": [
          "44px",
          { lineHeight: "54px", letterSpacing: "0em", fontWeight: "400" },
        ],
        display: [
          "64px",
          { lineHeight: "76px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-mobile": [
          "40px",
          { lineHeight: "48px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-sm": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
